<!--	UPDATE var $host (hostname), $user (username for accessing db) and $db (dbname), $password (MySQL password) -->
<?php
class JConfig {
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '1';
	var $sef_rewrite = '1';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = '4fYOLZvWqoMfqT4J';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = 'C:\\xampp\\htdocs\\technix\\logs';
	var $tmp_path = 'C:\\xampp\\htdocs\\technix\\tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = '';
	var $user = '';
	var $db = '';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'admin@gectechnix.in';
	var $fromname = 'Technix';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '15';
	var $session_handler = 'database';
	var $password = '';
	var $sitename = 'Technix - Annual Techfest of Goa College Of Engineering';
	var $MetaDesc = 'Technix- The Annual Techfest of Goa College of Engineering, Ponda, Goa, India, organised by the Computer Students\' Organisation (CURSOR)';
	var $MetaKeys = 'technix,goa,techfest,india,engineering,technology,computers,cursor,gec,engico,technix 5.0,farmagudi,ponda,college';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
}
?>